server:
  port: 8082
spring:
  application:
    name: File Connector(Source)
  cloud:
    stream:
      bindings:
        input-0:
          destination: /home/kvaishnav/solacego/2.3.0/pubsubplus-connector-file-2.3.0/samples/config/source/multifiles.cfg
          binder: file
        output-0:
          destination: nse/dd/prod/orderbook/TEST_ADAPTER_R1
          binder: solace
file:
  source:
    scheduler:
      restart_time_sec: 10
    general:
      adapter_id: TEST_ADAPTER_ID1
      file_type: 4
      state_backup_path: backup_state.cfg
      ignoreEmptyFiles: false
      copy_file_mode_permissions: 0
      max_file_transfer_size: 999000
      max_files_allowed: 99999
      max_bandwidth_limit: 0
      clear_state_on_eod: 0
      eod_time_sec: -1
    file_to_event:
      enabled: 0
      fileFormat: 4
      eventDelimiter: '|'
      #paramDelimiter: ','
      #dynamicTopic: solace/fc/source/test/dynamic/{param-3}/{param-4}/{param-5}/{event_no}/{param-4}
      #paramHeaderMap: event_no,connector,col3,new_param,message
      jsonPath: '$.Authors[*].Books[*]'
      xPath: '/class/student'
    gcs:
      enabled: 0
      projectId: GCS_PROJECT_ID
      credentialsFilePath: /home/centos/pubsubplus-connector-file-2.2.0/configs/gcs/creds.json
      retrySettings:
        maxAttempts: 5
        retryDelayMultiplier: 3.0
        maxDurationMinutes: 2
    sftp_settings:
      enabled: 0
      ip: SFTP_HOST_ADDRESS
      port: 22
      user: SFTP_USER
      password: SFTP_PASSWORD
      strictHostKeyChecking: no
      #privateKeyPath: /home/centos/.ssh/id_rsa
    ftp_settings:
      enabled: 0
      ip: FTP_HOST_ADDRESS
      port: 21
      user: FTP_USER
      password: FTP_PASSWORD
      secured: true
    directory_wildcard:
      wildcard_type: 0
      config_path: /home/kvaishnav/solacego/2.3.0/pubsubplus-connector-file-2.3.0/samples/config/dir_regexps.conf
    directory_replication:
      start_time: -1
    solace_out:
      lvq: lvq.TEST_ADAPTER_R1
      destination: nse/dd/prod/orderbook/TEST_ADAPTER_R1
    command_center:
      enabled: 0
      useOutputDestinationSolaceCredentials: true
      heartbeat_enabled: 0
      heartbeat_interval: 3
      solace_base_publish_topic_heartbeat: solace/dd/STORE-MANGEMENT/fa-segmenter/cc/se/fa/segmenter/Stockholm
      solace_base_publish_topic: solace/dd/STORE-MANGEMENT/fa-segmenter/cc/se/fa/segmenter/Stockholm
      solace_messaging_mode: PERSISTENT
      events:
        fileStart: true
        fileComplete: true
solace:
  connector:
    error:
      handle: stop_all
    workflows:
      0:
        enabled: true
        acknowledgment:
          publish-async: true
    management:
      leader-election:
        mode: standalone  # The connectorâ€™s leader election mode. (values: standalone, active_active, active_standby)
        fail-over:
          max-attempts: 3  # The maximum number of attempts to perform a fail-over.
          back-off-initial-interval: 1000  # The initial interval (milliseconds) to back-off when retrying a fail-over.
          back-off-max-interval: 10000  # The maximum interval (milliseconds) to back-off when retrying a fail-over.
          back-off-multiplier: 2.0  # The multiplier to apply to the back-off interval between each retry of a fail-over.
      queue: q.test  # The management queue name.
      session: # The management session. This has the same interface as that used by `solace.java.*`. For more info: https://github.com/SolaceProducts/solace-spring-boot/tree/master/solace-spring-boot-starters/solace-java-spring-boot-starter#updating-your-application-properties
        host: tcp://localhost:55555
        msg-vpn: default
        client-username: default
        client-password: default
  java:
    host: tcp://localhost:55555
    msg-vpn: default
    client-username: default
    client-password: default
    connectRetries: -1
    reconnectRetries: -1
logging:  # Logging configuration. For more info: https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging
  level:
    root: INFO
    com.solace.connector.jms: INFO # Enables TRACE logs for connector
    com.solace.connector.core: INFO # Enables TRACE logs for connector framework
    com.solace.spring.cloud.stream.binder: INFO # Enables TRACE logs for Solace and JMS binders
    com.solacecoe.spring.cloud.stream.binders.file: TRACE # Enables TRACE logs for Solace and JMS binders
  file:
    name: /home/kvaishnav/solacego/2.3.0/pubsubplus-connector-file-2.3.0/samples/config/source/myapp.log  # base log file name
  logback:
    rollingpolicy:  # Logback file rolling policy
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"  # Pattern for rolled-over log file names. Example: Rolls the log file into an archive once every day. `%i` is reset to `0` at the start of the day.
      max-file-size: 100MB  # The maximum size of log file before it is archived. Example: Within a given day, when the log file reaches 100 MB, archive it, and increment `%i`.
      max-history: 7  # The maximum rotation-period's worth of archive log files to keep. Example: Since the `file-name-pattern` is configured to rollover once every day, keep 7 days worth of log archives.
      total-size-cap: 1GB  # Total size of log backups for a given rotation period. Example: Keep up-to 1 GB of log archives for every day.
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: myapp.log
    prometheus:
      enabled: false
    health:
      show-details: ALWAYS
      status:
        # Change default order so that RECONNECTING takes precedence over UP and UNKNOWN
        order:
          - DOWN
          - OUT_OF_SERVICE
          - RECONNECTING
          - UP
          - UNKNOWN