apiVersion: apps/v1
kind: Deployment
metadata:
  name: solace-consumer
  namespace: solace
spec:
  replicas: 0
  selector:
    matchLabels:
      app: solace-consumer
  template:
    metadata:
      labels:
        app: solace-consumer
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: consumer
        image: ghcr.io/khushal-vaishnav/solace-consumer:1.0
        envFrom:
        - configMapRef:
            name: solace-app-config
        - secretRef:
            name: solace-app-secret

