apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solace-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Khushal-vaishnav/solacepubsub-go.git
    targetRevision: main
    path: solace-gitops/solace   # âœ… THIS MATCHES YOUR TREE

  destination:
    server: https://kubernetes.default.svc
    namespace: solace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

